version: '3.9'
services:
  wordfluxDb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5456:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  dotnetapp:
    image: wordflux-apiservice:latest
    depends_on:
      - wordfluxDb
    environment:
      ConnectionStrings__postgresdb: "Host=wordfluxDb;Port=5432;Database=mydatabase;Username=postgres;Password=postgres"
    ports:
      - "5009:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
